# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_dialog(object):
    def setupUi(self, dialog):
        dialog.setObjectName("dialog")
        dialog.resize(352, 524)
        dialog.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        dialog.setMouseTracking(False)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("toiney.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        dialog.setWindowIcon(icon)
        dialog.setLayoutDirection(QtCore.Qt.LeftToRight)
        dialog.setSizeGripEnabled(False)
        dialog.setModal(False)
        self.tab_widget = QtWidgets.QTabWidget(dialog)
        self.tab_widget.setGeometry(QtCore.QRect(0, 0, 331, 511))
        self.tab_widget.setObjectName("tab_widget")
        self.account_tab = QtWidgets.QWidget()
        self.account_tab.setObjectName("account_tab")
        self.frame = QtWidgets.QFrame(self.account_tab)
        self.frame.setGeometry(QtCore.QRect(0, -10, 351, 511))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(0, 10, 81, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(0, 40, 81, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.firstName = QtWidgets.QLineEdit(self.frame)
        self.firstName.setGeometry(QtCore.QRect(90, 10, 133, 20))
        self.firstName.setObjectName("firstName")
        self.lastName = QtWidgets.QLineEdit(self.frame)
        self.lastName.setGeometry(QtCore.QRect(90, 40, 133, 20))
        self.lastName.setObjectName("lastName")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(0, 80, 81, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setGeometry(QtCore.QRect(0, 110, 81, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setGeometry(QtCore.QRect(0, 140, 81, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.birthDay = QtWidgets.QLineEdit(self.frame)
        self.birthDay.setGeometry(QtCore.QRect(90, 140, 133, 20))
        self.birthDay.setObjectName("birthDay")
        self.label_7 = QtWidgets.QLabel(self.frame)
        self.label_7.setGeometry(QtCore.QRect(0, 210, 81, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.frame)
        self.label_8.setGeometry(QtCore.QRect(0, 250, 81, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.birthYear = QtWidgets.QLineEdit(self.frame)
        self.birthYear.setGeometry(QtCore.QRect(90, 80, 133, 20))
        self.birthYear.setObjectName("birthYear")
        self.birthMonth = QtWidgets.QLineEdit(self.frame)
        self.birthMonth.setGeometry(QtCore.QRect(90, 110, 133, 20))
        self.birthMonth.setObjectName("birthMonth")
        self.countryCode = QtWidgets.QComboBox(self.frame)
        self.countryCode.setGeometry(QtCore.QRect(90, 250, 131, 21))
        self.countryCode.setObjectName("countryCode")
        self.email = QtWidgets.QLineEdit(self.frame)
        self.email.setGeometry(QtCore.QRect(90, 330, 133, 20))
        self.email.setObjectName("email")
        self.password = QtWidgets.QLineEdit(self.frame)
        self.password.setGeometry(QtCore.QRect(90, 360, 133, 20))
        self.password.setObjectName("password")
        self.label_9 = QtWidgets.QLabel(self.frame)
        self.label_9.setGeometry(QtCore.QRect(0, 330, 81, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.frame)
        self.label_10.setGeometry(QtCore.QRect(0, 360, 81, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.ethnicityBox = QtWidgets.QComboBox(self.frame)
        self.ethnicityBox.setGeometry(QtCore.QRect(90, 210, 131, 21))
        self.ethnicityBox.setObjectName("ethnicityBox")
        self.label_11 = QtWidgets.QLabel(self.frame)
        self.label_11.setGeometry(QtCore.QRect(0, 280, 81, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.zipCode = QtWidgets.QLineEdit(self.frame)
        self.zipCode.setGeometry(QtCore.QRect(90, 280, 133, 20))
        self.zipCode.setObjectName("zipCode")
        self.label_12 = QtWidgets.QLabel(self.frame)
        self.label_12.setGeometry(QtCore.QRect(0, 180, 81, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.genderBox = QtWidgets.QComboBox(self.frame)
        self.genderBox.setGeometry(QtCore.QRect(90, 180, 131, 21))
        self.genderBox.setObjectName("genderBox")
        self.genderBox.addItem("")
        self.genderBox.addItem("")
        self.buttonBox = QtWidgets.QDialogButtonBox(self.frame)
        self.buttonBox.setGeometry(QtCore.QRect(160, 450, 156, 23))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.label_13 = QtWidgets.QLabel(self.frame)
        self.label_13.setGeometry(QtCore.QRect(0, 400, 81, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.photoPath = QtWidgets.QLineEdit(self.frame)
        self.photoPath.setGeometry(QtCore.QRect(80, 400, 191, 21))
        self.photoPath.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.photoPath.setDragEnabled(False)
        self.photoPath.setReadOnly(True)
        self.photoPath.setObjectName("photoPath")
        self.photoBtn = QtWidgets.QToolButton(self.frame)
        self.photoBtn.setGeometry(QtCore.QRect(280, 400, 31, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.photoBtn.sizePolicy().hasHeightForWidth())
        self.photoBtn.setSizePolicy(sizePolicy)
        self.photoBtn.setObjectName("photoBtn")
        self.tab_widget.addTab(self.account_tab, "")
        self.device_tab = QtWidgets.QWidget()
        self.device_tab.setObjectName("device_tab")
        self.tab_widget.addTab(self.device_tab, "")

        self.retranslateUi(dialog)
        self.tab_widget.setCurrentIndex(0)
        self.buttonBox.accepted.connect(dialog.accept)
        self.buttonBox.rejected.connect(dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(dialog)

    def retranslateUi(self, dialog):
        _translate = QtCore.QCoreApplication.translate
        dialog.setWindowTitle(_translate("dialog", "Toiney v1.0"))
        self.label.setText(_translate("dialog", "* First name:"))
        self.label_3.setText(_translate("dialog", "* Last name:"))
        self.label_4.setText(_translate("dialog", "* Birth year"))
        self.label_5.setText(_translate("dialog", "* Birth month"))
        self.label_6.setText(_translate("dialog", "* Birth day:"))
        self.label_7.setText(_translate("dialog", "* Ethnicity:"))
        self.label_8.setText(_translate("dialog", "* Country:"))
        self.label_9.setText(_translate("dialog", "* Email:"))
        self.label_10.setText(_translate("dialog", "* Password:"))
        self.label_11.setText(_translate("dialog", "* Zipcode:"))
        self.label_12.setText(_translate("dialog", "* Gender:"))
        self.genderBox.setItemText(0, _translate("dialog", "F"))
        self.genderBox.setItemText(1, _translate("dialog", "M"))
        self.label_13.setText(_translate("dialog", "* Photo path:"))
        self.photoBtn.setText(_translate("dialog", "..."))
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.account_tab), _translate("dialog", "Account"))
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.device_tab), _translate("dialog", "Device"))

